[platformio]
; 大陆地区源配置

; 库源配置
lib_registry = https://registry.platformio.org

; 下载镜像
; 使用国内镜像

; 全局代理设置
; 如果需要代理，可以在这里设置
; proxy_http = http://127.0.0.1:7890
; proxy_https = http://127.0.0.1:7890

; 自定义库搜索路径
; 可以添加本地库路径，避免从网络下载
lib_dir = .pio/lib