#ifndef CONFIG_H
#define CONFIG_H

// Platform macros
#define PLATFORM_ESP32 1
#define PLATFORM_ESP8266 0
#define PLATFORM_NRF52 0
#define PLATFORM_STM32 0
#define PLATFORM_RP2040 0

// Audio module macros
#define AUDIO_DRIVER_TYPE AUDIO_DRIVER_ESP32_AUDIO

// WiFi+Bluetooth module macros
#define WIFI_BT_MODULE_TYPE WIFI_BT_INTERNAL
#define HAS_WIFI_BT 1

// TF card reader macros
#define TF_CARD_READER_TYPE TF_READER_NONE
#define HAS_TF_CARD 0

// Display macros
#define DISPLAY_TYPE EINK_42_INCH_HEMA

// Sensor macros
#define ENABLE_DHT22 1
#define ENABLE_SHT30 0
#define ENABLE_BH1750 0
#define ENABLE_HC_SR501 1
#define ENABLE_MQ135 0
#define ENABLE_IR_FLAME 1
#define ENABLE_BME280 0

// Hardware module macros
#define ENABLE_TF_CARD 0
#define ENABLE_CAMERA 0

// Feature macros
#define ENABLE_ALARM_DISPLAY 1
#define ENABLE_TEMPERATURE_HUMIDITY_DISPLAY 1
#define ENABLE_BLUETOOTH 1
#define ENABLE_TF_CARD_MANAGEMENT 1
#define ENABLE_PLUGIN 1
#define ENABLE_WEBCLIENT 1
#define ENABLE_FIRMWARE 1
#define ENABLE_AUDIO 1
#define ENABLE_VOICE_MESSAGE 1
#define ENABLE_TOUCH 0
#define ENABLE_VIDEO_MESSAGE 0
#define ENABLE_TEXT_MESSAGE 1
#define ENABLE_FONT 0
#define ENABLE_WIFI 1
#define ENABLE_MOTION_SAVING 1

#endif // CONFIG_H // CONFIG_H // CONFIG_H // CONFIG_H // CONFIG_H // CONFIG_H