#ifndef CONFIG_H
#define CONFIG_H

// Platform macros
#define PLATFORM_ESP32 1
#define PLATFORM_ESP8266 0
#define PLATFORM_NRF52 0
#define PLATFORM_STM32 0
#define PLATFORM_RP2040 0

// Audio module macros
#define AUDIO_DRIVER_TYPE AUDIO_DRIVER_NONE

// WiFi+Bluetooth module macros
#define WIFI_BT_MODULE_TYPE WIFI_BT_INTERNAL
#define HAS_WIFI_BT 1

// TF card reader macros
#define TF_CARD_READER_TYPE TF_READER_NONE
#define HAS_TF_CARD 0

// Display macros
#define DISPLAY_TYPE EINK_42_INCH_HEMA

// Sensor macros
#define ENABLE_DHT22 0
#define ENABLE_AM2302 0
#define ENABLE_SHT20 0
#define ENABLE_SHT30 0
#define ENABLE_SHT40 0
#define ENABLE_HDC1080 0
#define ENABLE_BME280 0
#define ENABLE_BME680 0
#define ENABLE_HC_SR501 0
#define ENABLE_HC_SR505 0
#define ENABLE_RCWL_0516 0
#define ENABLE_LD2410 0
#define ENABLE_MQ2 0
#define ENABLE_MQ5 0
#define ENABLE_MQ7 0
#define ENABLE_MQ135 0
#define ENABLE_SGP30 0
#define ENABLE_IR_FLAME 0
#define ENABLE_YG1006 0
#define ENABLE_UV_FLAME 0
#define ENABLE_LPS25HB 0
#define ENABLE_BMP388 0

// Hardware module macros
#define ENABLE_TF_CARD 0
#define ENABLE_CAMERA_GC0308 0
#define ENABLE_CAMERA_OV2640 0
#define ENABLE_CAMERA_OV5640 0
#define ENABLE_CAMERA_ESP32_CAM 0

// Feature macros
#define ENABLE_FONT 0
#define ENABLE_AUDIO 0
#define ENABLE_TEXT_MESSAGE 1
#define ENABLE_VIDEO_MESSAGE 0
#define ENABLE_TEMPERATURE_HUMIDITY_DISPLAY 0
#define ENABLE_FIRMWARE 1
#define ENABLE_VOICE_MESSAGE 0
#define ENABLE_MOTION_SAVING 0
#define ENABLE_BLUETOOTH 1
#define ENABLE_WEBCLIENT 1
#define ENABLE_FIRE_ALARM 0
#define ENABLE_LIGHT_SAVING 0
#define ENABLE_PLUGIN 1
#define ENABLE_TOUCH 0
#define ENABLE_GAS_ALARM 0
#define ENABLE_WIFI 1

// Power management macros
#define LOW_POWER_MODE_ENABLED 0
#define NO_MOTION_TIMEOUT 30000
#define NIGHT_LIGHT_THRESHOLD 100
#define LIGHT_CHANGE_THRESHOLD 50
#define NORMAL_REFRESH_INTERVAL 60000
#define LOW_POWER_REFRESH_INTERVAL 300000
// 新增：电量临界阈值和刷新间隔
#define CRITICAL_BATTERY_THRESHOLD 10
#define CRITICAL_LOW_POWER_REFRESH_INTERVAL 600000
#define MIN_REFRESH_INTERVAL 10000
#define MAX_REFRESH_INTERVAL 3600000

// 电池电压定义
#define FULL_BATTERY_VOLTAGE 4.2
#define EMPTY_BATTERY_VOLTAGE 3.0
#define LOW_BATTERY_THRESHOLD 20

// 充电相关定义
#define CHARGING_PROTECTION_ENABLED 1
#define CHARGING_POWER_MIN 5.0
#define CHARGING_POWER_MAX 18.0
#define DC_POWER_SUPPORTED 0
#define ONLY_USB_POWER_SUPPORTED 1

// 充电状态引脚定义
#define CHARGE_STATUS_PIN -1
#define BATTERY_ADC_PIN 34

// 人体感应传感器引脚定义
#define PIR_SENSOR_PIN -1

// 光照传感器引脚定义
#define LIGHT_SENSOR_PIN -1

// 气体传感器引脚定义
#define GAS_SENSOR_PIN -1

// 火焰传感器引脚定义
#define FLAME_SENSOR_PIN -1

// 充电接口类型
#define ChargingInterfaceType enum {
  USB_TYPE_A,
  USB_TYPE_C,
  USB_TYPE_B,
  DC_JACK
};

// 充电接口类型
#define ChargingInterfaceType enum {
  USB_TYPE_A,
  USB_TYPE_C,
  USB_TYPE_B,
  DC_JACK
};

// 充电保护电路状态
#define ChargingProtectionStatus enum {
  PROTECTION_OK,
  PROTECTION_OVER_VOLTAGE,
  PROTECTION_OVER_CURRENT,
  PROTECTION_OVER_TEMPERATURE,
  PROTECTION_SHORT_CIRCUIT
};

#endif // CONFIG_H // CONFIG_H // CONFIG_H // CONFIG_H // CONFIG_H // CONFIG_H // CONFIG_H // CONFIG_H // CONFIG_H // CONFIG_H